primary:
  persistence:
    size: 8Gi
    enabled: true
    deleteClaim: true
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
  podLabels:
    app: xp-postgres

auth:
  username: postgres-username
  password: postgres-password
  database: postgres-database